displayName: TritonPlugin
type: middleware
iconPath: .assets/icon.png

import: github.com/wrpromail/RequestPeekPlugin

summary: 'Traefik Plugin for Peeking Request Content'

testData:
  report_type: "UDP"
  report_addr: ""

  reject_probability: 0.2
